#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${IMAGE_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${IMAGE_DB_USERNAME}'@'%' IDENTIFIED BY '${IMAGE_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${IMAGE_DB_NAME}\`.* TO '${IMAGE_DB_USERNAME}'@'%';
    
    CREATE DATABASE IF NOT EXISTS \`${RECIPE_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${RECIPE_DB_USERNAME}'@'%' IDENTIFIED BY '${RECIPE_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${RECIPE_DB_NAME}\`.* TO '${RECIPE_DB_USERNAME}'@'%';

    CREATE DATABASE IF NOT EXISTS \`${IDENTITY_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${IDENTITY_DB_USERNAME}'@'%' IDENTIFIED BY '${IDENTITY_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${IDENTITY_DB_NAME}\`.* TO '${IDENTITY_DB_USERNAME}'@'%';

    FLUSH PRIVILEGES;
EOSQL