# Application variables
JWT_SECRET=YOUR_RANDOM_32_BYTE_SECRET
DEFAULT_ADMIN_PASSWORD=YOUR_DESIRED_PASSWORD

# Database connection details
DB_HOST=localhost
DB_PORT=3306
DB_NAME=recipe_repository
DB_USERNAME=recipe_repository
DB_PASSWORD=YOUR_DESIRED_PASSWORD