RECIPE_SERVICE_URL=http://localhost:8081
IDENTITY_SERVICE_URL=http://localhost:8082

APP_KEYCLOAK_JWK_SET_URI=http://localhost:9000/realms/recipe-repository/protocol/openid-connect/certs
APP_KEYCLOAK_ISSUER_URI=http://localhost:9000/realms/recipe-repository