KEYCLOAK_ADMIN=YOUR_KC_ADMIN_USER
KEYCLOAK_ADMIN_PASSWORD=YOUR_KC_ADMIN_PASSWORD

KC_DB=postgres
KC_DB_URL=jdbc:postgresql://recipe-repository-postgres-keycloak:5432/keycloak
KC_DB_USERNAME=YOUR_KC_DB_ADMIN_USERNAME
KC_DB_PASSWORD=YOUR_KC_DB_ADMIN_PASSWORD