DB_HOST=localhost
DB_PORT=33306
DB_NAME=rr_images
DB_USERNAME=rr_images
DB_PASSWORD=YOUR_DB_PASSWORD

APP_KEYCLOAK_JWK_SET_URI=http://localhost:9000/realms/recipe-repository/protocol/openid-connect/certs
APP_KEYCLOAK_ISSUER_URI=http://localhost:9000/realms/recipe-repository