MYSQL_ROOT_PASSWORD=...

RECIPE_DB_NAME=rr_recipes
RECIPE_DB_USERNAME=rr_recipes
RECIPE_DB_PASSWORD=YOUR_RECIPE_DB_PASSWORD

IDENTITY_DB_NAME=rr_identity
IDENTITY_DB_USERNAME=rr_identity
IDENTITY_DB_PASSWORD=YOUR_IDENTITY_DB_PASSWORD