DB_HOST=localhost
DB_PORT=3306
DB_NAME=rr_identity
DB_USERNAME=rr_identity
DB_PASSWORD=YOUR_DB_PASSWORD

IMAGE_SERVICE_URI=http://localhost:8082

APP_KEYCLOAK_URI=http://localhost:9000
APP_KEYCLOAK_REALM=recipe-repository

APP_KEYCLOAK_SERVICE_CLIENT_ID=YOUR_SERVICE_CLIENT_ID
APP_KEYCLOAK_SERVICE_CLIENT_SECRET=YOUR_SERVICE_CLIENT_SECRET

APP_KEYCLOAK_ISSUER_URI=${APP_KEYCLOAK_URI}/realms/${APP_KEYCLOAK_REALM}
APP_KEYCLOAK_JWK_SET_URI=${APP_KEYCLOAK_URI}/realms/${APP_KEYCLOAK_REALM}/protocol/openid-connect/certs