# Application MySQL connection details
MYSQL_DATABASE=recipe_repository
MYSQL_USER=recipe_repository
MYSQL_PASSWORD=YOUR_DB_PASSWORD

# Root password for accessing MySQL
MYSQL_ROOT_PASSWORD=YOUR_ROOT_PASSWORD