export enum TransportErrorCode {
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE',
}

export enum ErrorCode {
  // Internals
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  MESSAGE_NOT_READABLE = 'MESSAGE_NOT_READABLE',
  MESSAGE_NOT_WRITABLE = 'MESSAGE_NOT_WRITABLE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  MISSING_PARAMETERS = 'MISSING_PARAMETERS',

  // Authentication
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  AUTH_USER_LOCKED = 'AUTH_USER_LOCKED',
  AUTH_USER_BLOCKED = 'AUTH_USER_BLOCKED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',

  // Recipes
  DUPLICATE_RECIPE = 'DUPLICATE_RECIPE',
  RECIPE_NOT_FOUND = 'RECIPE_NOT_FOUND',
  RECIPE_MISMATCH = 'RECIPE_MISMATCH',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_USERNAME = 'DUPLICATE_USERNAME',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INCORRECT_NEW_PASSWORD = 'INCORRECT_NEW_PASSWORD',
}
