services:
  recipe-repository-mysql:
    container_name: recipe-repository-mysql
    image: mysql:8.0.40
    env_file: "../secrets/mysql.properties"
    ports:
      - "3306:3306"
    volumes:
      - recipe_repository_mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - backend

  recipe-repository-redis:
    container_name: recipe-repository-redis
    image: redis:8.10.1-alpine
    ports:
      - "6379:6379"
    command: "--save 60 1"
    volumes:
      - recipe_repository_redis_data:/data

volumes:
  recipe_repository_mysql_data:
  recipe_repository_redis_data:

networks:
  backend:
    driver: bridge
