services:
  recipe-repository-mysql:
    container_name: recipe-repository-mysql
    image: mysql:8.0.40
    env_file: "../secrets/mysql.properties"
    ports:
      - "3306:3306"
    volumes:
      - recipe_repository_mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    networks:
      - backend

  recipe-repository-keycloak:
    container_name: recipe-repository-keycloak
    image: quay.io/keycloak/keycloak:latest
    env_file: "../secrets/keycloak.properties"
    ports:
      - "9000:8080"
    command: [ "start-dev" ]
    networks:
      - backend


  recipe-repository-postgres-keycloak:
    container_name: recipe-repository-postgres-keycloak
    image: postgres:18.4-alpine
    env_file: "../secrets/postgres-keycloak.properties"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - recipe_repository_keycloak_data:/var/lib/postgresql
    command: postgres -c 'max_connections=500'
    networks:
      - backend

volumes:
  recipe_repository_mysql_data:
  recipe_repository_keycloak_data:

networks:
  backend:
    driver: bridge
