server:
  port: 8080

spring:
  config:
    import: optional:file:./secrets/gateway.properties

  application:
    name: 'gateway'

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: recipe-service-route
              uri: ${RECIPE_SERVICE_URI}
              predicates:
                - Path=/api/v1/recipes/**

            - id: identity-service-route
              uri: ${IDENTITY_SERVICE_URI}
              predicates:
                - Path=/api/v1/identity/**

            - id: image-service-route
              uri: ${IMAGE_SERVICE_URI}
              predicates:
                - Path=/api/v1/images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${APP_KEYCLOAK_JWK_SET_URI}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web.servlet: DEBUG