server:
  port: 8080

spring:
  application:
    name: 'gateway'

  config:
    import: file:./secrets/app-env.properties

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: recipe-service-route
              uri: ${RECIPE_SERVICE_URL}
              predicates:
                - Path=/api/v1/recipes/**

            - id: identity-service-route
              uri: ${IDENTITY_SERVICE_URL}
              predicates:
                - Path=/api/v1/identity/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${APP_KEYCLOAK_JWK_SET_URI}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE