app:
  aws:
    s3:
      bucket-name: recipe-repository-dev

  mail:
    reply-to: ${EMAIL_REPLY_TO}

  name: Recipe Repository
  password-reset-url: http://localhost:4200/app/auth/reset-password?token=

  security:
    default-admin-password: ${DEFAULT_ADMIN_PASSWORD}
    jwt-secret: ${JWT_SECRET}

server:
  port: 8080
  forward-headers-strategy: native

spring:
  config:
    import: optional:file:./secrets/app.properties

  application:
    name: recipe-repository

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: false
        format_sql: true
        use_sql_comments: true
        generate_statistics: false

  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always

  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.orm.connections.pooling: ERROR
    org.springframework.jdbc.core: INFO
    org.springframework.jdbc.core.namedparam: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBindeR: INFO
    com.fasterxml.jackson.databind: INFO
    org.springframework.http.converter: INFO
    org.springframework.web.servlet.mvc.method.annotation: INFO