name: Back-end Pipeline
on:
  push:
    branches: [ main, test ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out Github repository
        uses: actions/checkout@v4
        with: 
            sparse-checkout: backend
          
      - name: Create env.properties
        env:
            PROPERTIES: ${{ secrets.BACKEND_PROPERTIES }}
        run: echo "$PROPERTIES" > env.properties

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven project
        run: mvn --batch-mode --update-snapshots verify

      - name: Deliver snapshot
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_AWS_EC2 }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS_AWS_EC2 }}
          HOST: ${{ secrets.SSH_HOST_AWS_EC2 }}
        run: |
            mkdir ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            chmod 400 ~/.ssh/id_rsa
            
            eval $(ssh-agent)
            ssh-add - <<< "$SSH_KEY"
            
            scp target/reciperepository-0.0.1-SNAPSHOT.jar env.properties "$HOST":~/recipe-repository/
        
      # This is very rudimentary and "just gets the job done" - I'll improve on it later.
      - name: Deploy snapshot
        shell: bash
        env:
          HOST: ${{ secrets.SSH_HOST_AWS_EC2 }}
        run: |
          ssh "$HOST" 'pidof java | xargs kill || true'
          ssh "$HOST" 'cd ~/recipe-repository/ && (nohup java -jar -XX:+UseSerialGC reciperepository-0.0.1-SNAPSHOT.jar > nohup.out 2> nohup.err < /dev/null &)'