name: Recipe Repository frontend workflow
on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out Github repository
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
    
      - name: Install dependencies
        run: npm ci
        
      - name: Run karma tests
        run: npm run test-ci
        
      - name: Build for production
        run: npm run build-prod
        
    #  - name: Copy output to remote server